receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55681

exporters:
  jaeger:
    endpoint: "http://jaeger:14268/api/traces"
    insecure: true

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
