receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55681

exporters:
  otlp/tempo:
    endpoint: "http://tempo:4318"
    insecure: true

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
